-- WoWKillboard_RealmData.lua
-- Automated Realm Intelligence & Two-Way Sync generated by WoWKillboardSync
WoWKillboard_RealmData = {
    RealmTotalCarnage = 0,
    SoloRatio = 0.0,
    FactionSplit = {
        Alliance = 50.0,
        Horde = 50.0,
    },
    DeadliestZones = {},
    TopGankers24h = {},
    RecentKills = {},
    ActiveBounties = {},
    RecentPveDeaths = {},
    PveTotalDeaths = 0,
    PveTopExecutioners = {},
    PveTopVictims = {},
    PveDeadliestZone = {
        deaths = 0,
        zone = "None",
    },
    LastSync = 1790906729,
}
