-- WoWKillboard_RealmData.lua
-- Automated Realm Intelligence generated by WoWKillboardSync
WoWKillboard_RealmData = {
    RealmTotalCarnage = 26,
    SoloRatio = 15.4,
    FactionSplit = {
        Alliance = 88.5,
        Horde = 11.5,
    },
    DeadliestZones = {
        { zone = "Arathi Highlands", kills = 1 },
    },
    TopGankers24h = {
        { name = "Dagariane", class = "PALADIN", faction = "Alliance", guild = "None", kills = 1 },
    },
    LastSync = 1790718499,
}
