-- WoWKillboard_RealmData.lua
-- Automated Realm Intelligence & Two-Way Sync generated by WoWKillboardSync
WoWKillboard_RealmData = {
    RealmTotalCarnage = 0,
    SoloRatio = 0.0,
    FactionSplit = {
        Alliance = 50.0,
        Horde = 50.0,
    },
    DeadliestZones = {},
    TopGankers24h = {},
    RecentKills = {},
    ActiveBounties = {},
    RecentPveDeaths = {},
    PveTotalDeaths = 0,
    PveTopExecutioners = {},
    PveTopVictims = {},
    PveDeadliestZone = {
        deaths = 0,
        zone = "None",
    },
    LatestVersion = "1.0.3",
    Changelog = {
        "Dynamic Accent Color Engine (Classic Gold, Class Color, Hex)",
        "ElvUI Minimalist Overhaul (1px Solid Borders & Clean Strips)",
        "Cross-Realm & Ruleset Isolation (PvP, PvE, RP, HC Segregation)",
        "Automated Theme Migration to Modern Flat Glass Architecture",
        "Dual GitHub Direct Releases & CurseForge App Links",
    },
    LastSync = 0,
}
